//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballAPPFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment_Report
    {
        public int ID { get; set; }
        public int CommentID { get; set; }
        public int TaskID { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual Task Task { get; set; }
    }
}
